package sap

type BusinessPartner struct {
	OdataContext string `json:"@odata.context,omitempty"`
	CardCode     string
	CardName     string
	FederalTaxID string
	Phone1       string
	Phone2       string
	EmailAddress string
	Address      string
	ZipCode      string
	City         string
	Country      string
	CardType     string `json:"CardType,omitempty"`
}

type Invoice struct {
	DocDate       string        `json:"DocDate"`
	DocDueDate    string        `json:"DocDueDate"`
	CardCode      string        `json:"CardCode"`
	Comments      string        `json:"Comments"`
	DocumentLines DocumentLines `json:"DocumentLines"`
}

type DocumentLines []DocumentLine

type DocumentLine struct {
	ItemCode        string `json:"ItemCode"`
	ItemDescription string `json:"ItemDescription,omitempty"`
	UnitPrice       string `json:"UnitPrice"`
	Quantity        string `json:"Quantity"`
	DiscountPercent string `json:"DiscountPercent"`
	VatRate         string `json:"VatRate"`
	FreeText        string `json:"FreeText"`
	PriceAfterVAT   string `json:"PriceAfterVAT"`
	ItemsGroupCode  string `json:"ItemsGroupCode"`
	Ccoste          string `json:"Ccoste"`
	Currency        string `json:"Currency"`
}

type Items []Item

type Item struct {
	ItemCode                         string      `json:"ItemCode"`
	ItemName                         string      `json:"ItemName"`
	ForeignName                      interface{} `json:"ForeignName"`
	ItemsGroupCode                   int         `json:"ItemsGroupCode"`
	CustomsGroupCode                 int         `json:"CustomsGroupCode"`
	SalesVATGroup                    interface{} `json:"SalesVATGroup"`
	BarCode                          interface{} `json:"BarCode"`
	VatLiable                        string      `json:"VatLiable"`
	PurchaseItem                     string      `json:"PurchaseItem"`
	SalesItem                        string      `json:"SalesItem"`
	InventoryItem                    string      `json:"InventoryItem"`
	IncomeAccount                    interface{} `json:"IncomeAccount"`
	ExemptIncomeAccount              interface{} `json:"ExemptIncomeAccount"`
	ExpanseAccount                   interface{} `json:"ExpanseAccount"`
	Mainsupplier                     interface{} `json:"Mainsupplier"`
	SupplierCatalogNo                interface{} `json:"SupplierCatalogNo"`
	DesiredInventory                 float64     `json:"DesiredInventory"`
	MinInventory                     float64     `json:"MinInventory"`
	Picture                          interface{} `json:"Picture"`
	UserText                         interface{} `json:"User_Text"`
	SerialNum                        interface{} `json:"SerialNum"`
	CommissionPercent                float64     `json:"CommissionPercent"`
	CommissionSum                    float64     `json:"CommissionSum"`
	CommissionGroup                  int         `json:"CommissionGroup"`
	TreeType                         string      `json:"TreeType"`
	AssetItem                        string      `json:"AssetItem"`
	DataExportCode                   interface{} `json:"DataExportCode"`
	Manufacturer                     int         `json:"Manufacturer"`
	QuantityOnStock                  float64     `json:"QuantityOnStock"`
	QuantityOrderedFromVendors       float64     `json:"QuantityOrderedFromVendors"`
	QuantityOrderedByCustomers       float64     `json:"QuantityOrderedByCustomers"`
	ManageSerialNumbers              string      `json:"ManageSerialNumbers"`
	ManageBatchNumbers               string      `json:"ManageBatchNumbers"`
	Valid                            string      `json:"Valid"`
	ValidFrom                        interface{} `json:"ValidFrom"`
	ValidTo                          interface{} `json:"ValidTo"`
	ValidRemarks                     interface{} `json:"ValidRemarks"`
	Frozen                           string      `json:"Frozen"`
	FrozenFrom                       interface{} `json:"FrozenFrom"`
	FrozenTo                         interface{} `json:"FrozenTo"`
	FrozenRemarks                    interface{} `json:"FrozenRemarks"`
	SalesUnit                        string      `json:"SalesUnit"`
	SalesItemsPerUnit                float64     `json:"SalesItemsPerUnit"`
	SalesPackagingUnit               string      `json:"SalesPackagingUnit"`
	SalesQtyPerPackUnit              float64     `json:"SalesQtyPerPackUnit"`
	SalesUnitLength                  float64     `json:"SalesUnitLength"`
	SalesLengthUnit                  interface{} `json:"SalesLengthUnit"`
	SalesUnitWidth                   float64     `json:"SalesUnitWidth"`
	SalesWidthUnit                   interface{} `json:"SalesWidthUnit"`
	SalesUnitHeight                  float64     `json:"SalesUnitHeight"`
	SalesHeightUnit                  interface{} `json:"SalesHeightUnit"`
	SalesUnitVolume                  float64     `json:"SalesUnitVolume"`
	SalesVolumeUnit                  int         `json:"SalesVolumeUnit"`
	SalesUnitWeight                  float64     `json:"SalesUnitWeight"`
	SalesWeightUnit                  interface{} `json:"SalesWeightUnit"`
	PurchaseUnit                     string      `json:"PurchaseUnit"`
	PurchaseItemsPerUnit             float64     `json:"PurchaseItemsPerUnit"`
	PurchasePackagingUnit            string      `json:"PurchasePackagingUnit"`
	PurchaseQtyPerPackUnit           float64     `json:"PurchaseQtyPerPackUnit"`
	PurchaseUnitLength               float64     `json:"PurchaseUnitLength"`
	PurchaseLengthUnit               interface{} `json:"PurchaseLengthUnit"`
	PurchaseUnitWidth                float64     `json:"PurchaseUnitWidth"`
	PurchaseWidthUnit                interface{} `json:"PurchaseWidthUnit"`
	PurchaseUnitHeight               float64     `json:"PurchaseUnitHeight"`
	PurchaseHeightUnit               interface{} `json:"PurchaseHeightUnit"`
	PurchaseUnitVolume               float64     `json:"PurchaseUnitVolume"`
	PurchaseVolumeUnit               int         `json:"PurchaseVolumeUnit"`
	PurchaseUnitWeight               float64     `json:"PurchaseUnitWeight"`
	PurchaseWeightUnit               interface{} `json:"PurchaseWeightUnit"`
	PurchaseVATGroup                 interface{} `json:"PurchaseVATGroup"`
	SalesFactor1                     float64     `json:"SalesFactor1"`
	SalesFactor2                     float64     `json:"SalesFactor2"`
	SalesFactor3                     float64     `json:"SalesFactor3"`
	SalesFactor4                     float64     `json:"SalesFactor4"`
	PurchaseFactor1                  float64     `json:"PurchaseFactor1"`
	PurchaseFactor2                  float64     `json:"PurchaseFactor2"`
	PurchaseFactor3                  float64     `json:"PurchaseFactor3"`
	PurchaseFactor4                  float64     `json:"PurchaseFactor4"`
	MovingAveragePrice               float64     `json:"MovingAveragePrice"`
	ForeignRevenuesAccount           interface{} `json:"ForeignRevenuesAccount"`
	ECRevenuesAccount                interface{} `json:"ECRevenuesAccount"`
	ForeignExpensesAccount           interface{} `json:"ForeignExpensesAccount"`
	ECExpensesAccount                interface{} `json:"ECExpensesAccount"`
	AvgStdPrice                      float64     `json:"AvgStdPrice"`
	DefaultWarehouse                 interface{} `json:"DefaultWarehouse"`
	ShipType                         interface{} `json:"ShipType"`
	GLMethod                         string      `json:"GLMethod"`
	TaxType                          string      `json:"TaxType"`
	MaxInventory                     float64     `json:"MaxInventory"`
	ManageStockByWarehouse           string      `json:"ManageStockByWarehouse"`
	PurchaseHeightUnit1              interface{} `json:"PurchaseHeightUnit1"`
	PurchaseUnitHeight1              float64     `json:"PurchaseUnitHeight1"`
	PurchaseLengthUnit1              interface{} `json:"PurchaseLengthUnit1"`
	PurchaseUnitLength1              float64     `json:"PurchaseUnitLength1"`
	PurchaseWeightUnit1              interface{} `json:"PurchaseWeightUnit1"`
	PurchaseUnitWeight1              float64     `json:"PurchaseUnitWeight1"`
	PurchaseWidthUnit1               interface{} `json:"PurchaseWidthUnit1"`
	PurchaseUnitWidth1               float64     `json:"PurchaseUnitWidth1"`
	SalesHeightUnit1                 interface{} `json:"SalesHeightUnit1"`
	SalesUnitHeight1                 float64     `json:"SalesUnitHeight1"`
	SalesLengthUnit1                 interface{} `json:"SalesLengthUnit1"`
	SalesUnitLength1                 float64     `json:"SalesUnitLength1"`
	SalesWeightUnit1                 interface{} `json:"SalesWeightUnit1"`
	SalesUnitWeight1                 float64     `json:"SalesUnitWeight1"`
	SalesWidthUnit1                  interface{} `json:"SalesWidthUnit1"`
	SalesUnitWidth1                  float64     `json:"SalesUnitWidth1"`
	ForceSelectionOfSerialNumber     string      `json:"ForceSelectionOfSerialNumber"`
	ManageSerialNumbersOnReleaseOnly string      `json:"ManageSerialNumbersOnReleaseOnly"`
	WTLiable                         string      `json:"WTLiable"`
	CostAccountingMethod             string      `json:"CostAccountingMethod"`
	Sww                              interface{} `json:"SWW"`
	WarrantyTemplate                 interface{} `json:"WarrantyTemplate"`
	IndirectTax                      string      `json:"IndirectTax"`
	ArTaxCode                        interface{} `json:"ArTaxCode"`
	ApTaxCode                        interface{} `json:"ApTaxCode"`
	BaseUnitName                     interface{} `json:"BaseUnitName"`
	ItemCountryOrg                   interface{} `json:"ItemCountryOrg"`
	IssueMethod                      string      `json:"IssueMethod"`
	SRIAndBatchManageMethod          string      `json:"SRIAndBatchManageMethod"`
	IsPhantom                        string      `json:"IsPhantom"`
	InventoryUOM                     string      `json:"InventoryUOM"`
	PlanningSystem                   string      `json:"PlanningSystem"`
	ProcurementMethod                string      `json:"ProcurementMethod"`
	ComponentWarehouse               string      `json:"ComponentWarehouse"`
	OrderIntervals                   interface{} `json:"OrderIntervals"`
	OrderMultiple                    float64     `json:"OrderMultiple"`
	LeadTime                         interface{} `json:"LeadTime"`
	MinOrderQuantity                 float64     `json:"MinOrderQuantity"`
	ItemType                         string      `json:"ItemType"`
	ItemClass                        string      `json:"ItemClass"`
	OutgoingServiceCode              int         `json:"OutgoingServiceCode"`
	IncomingServiceCode              int         `json:"IncomingServiceCode"`
	ServiceGroup                     int         `json:"ServiceGroup"`
	NCMCode                          int         `json:"NCMCode"`
	MaterialType                     string      `json:"MaterialType"`
	MaterialGroup                    int         `json:"MaterialGroup"`
	ProductSource                    string      `json:"ProductSource"`
	Properties1                      string      `json:"Properties1"`
	Properties2                      string      `json:"Properties2"`
	Properties3                      string      `json:"Properties3"`
	Properties4                      string      `json:"Properties4"`
	Properties5                      string      `json:"Properties5"`
	Properties6                      string      `json:"Properties6"`
	Properties7                      string      `json:"Properties7"`
	Properties8                      string      `json:"Properties8"`
	Properties9                      string      `json:"Properties9"`
	Properties10                     string      `json:"Properties10"`
	Properties11                     string      `json:"Properties11"`
	Properties12                     string      `json:"Properties12"`
	Properties13                     string      `json:"Properties13"`
	Properties14                     string      `json:"Properties14"`
	Properties15                     string      `json:"Properties15"`
	Properties16                     string      `json:"Properties16"`
	Properties17                     string      `json:"Properties17"`
	Properties18                     string      `json:"Properties18"`
	Properties19                     string      `json:"Properties19"`
	Properties20                     string      `json:"Properties20"`
	Properties21                     string      `json:"Properties21"`
	Properties22                     string      `json:"Properties22"`
	Properties23                     string      `json:"Properties23"`
	Properties24                     string      `json:"Properties24"`
	Properties25                     string      `json:"Properties25"`
	Properties26                     string      `json:"Properties26"`
	Properties27                     string      `json:"Properties27"`
	Properties28                     string      `json:"Properties28"`
	Properties29                     string      `json:"Properties29"`
	Properties30                     string      `json:"Properties30"`
	Properties31                     string      `json:"Properties31"`
	Properties32                     string      `json:"Properties32"`
	Properties33                     string      `json:"Properties33"`
	Properties34                     string      `json:"Properties34"`
	Properties35                     string      `json:"Properties35"`
	Properties36                     string      `json:"Properties36"`
	Properties37                     string      `json:"Properties37"`
	Properties38                     string      `json:"Properties38"`
	Properties39                     string      `json:"Properties39"`
	Properties40                     string      `json:"Properties40"`
	Properties41                     string      `json:"Properties41"`
	Properties42                     string      `json:"Properties42"`
	Properties43                     string      `json:"Properties43"`
	Properties44                     string      `json:"Properties44"`
	Properties45                     string      `json:"Properties45"`
	Properties46                     string      `json:"Properties46"`
	Properties47                     string      `json:"Properties47"`
	Properties48                     string      `json:"Properties48"`
	Properties49                     string      `json:"Properties49"`
	Properties50                     string      `json:"Properties50"`
	Properties51                     string      `json:"Properties51"`
	Properties52                     string      `json:"Properties52"`
	Properties53                     string      `json:"Properties53"`
	Properties54                     string      `json:"Properties54"`
	Properties55                     string      `json:"Properties55"`
	Properties56                     string      `json:"Properties56"`
	Properties57                     string      `json:"Properties57"`
	Properties58                     string      `json:"Properties58"`
	Properties59                     string      `json:"Properties59"`
	Properties60                     string      `json:"Properties60"`
	Properties61                     string      `json:"Properties61"`
	Properties62                     string      `json:"Properties62"`
	Properties63                     string      `json:"Properties63"`
	Properties64                     string      `json:"Properties64"`
	AutoCreateSerialNumbersOnRelease string      `json:"AutoCreateSerialNumbersOnRelease"`
	DNFEntry                         int         `json:"DNFEntry"`
	GTSItemSpec                      interface{} `json:"GTSItemSpec"`
	GTSItemTaxCategory               interface{} `json:"GTSItemTaxCategory"`
	FuelID                           int         `json:"FuelID"`
	BeverageTableCode                interface{} `json:"BeverageTableCode"`
	BeverageGroupCode                interface{} `json:"BeverageGroupCode"`
	BeverageCommercialBrandCode      int         `json:"BeverageCommercialBrandCode"`
	Series                           int         `json:"Series"`
	ToleranceDays                    interface{} `json:"ToleranceDays"`
	TypeOfAdvancedRules              string      `json:"TypeOfAdvancedRules"`
	IssuePrimarilyBy                 string      `json:"IssuePrimarilyBy"`
	NoDiscounts                      string      `json:"NoDiscounts"`
	AssetClass                       string      `json:"AssetClass"`
	AssetGroup                       string      `json:"AssetGroup"`
	InventoryNumber                  string      `json:"InventoryNumber"`
	Technician                       interface{} `json:"Technician"`
	Employee                         interface{} `json:"Employee"`
	Location                         interface{} `json:"Location"`
	AssetStatus                      string      `json:"AssetStatus"`
	CapitalizationDate               interface{} `json:"CapitalizationDate"`
	StatisticalAsset                 string      `json:"StatisticalAsset"`
	Cession                          string      `json:"Cession"`
	DeactivateAfterUsefulLife        string      `json:"DeactivateAfterUsefulLife"`
	ManageByQuantity                 string      `json:"ManageByQuantity"`
	UoMGroupEntry                    int         `json:"UoMGroupEntry"`
	InventoryUoMEntry                int         `json:"InventoryUoMEntry"`
	DefaultSalesUoMEntry             interface{} `json:"DefaultSalesUoMEntry"`
	DefaultPurchasingUoMEntry        interface{} `json:"DefaultPurchasingUoMEntry"`
	DepreciationGroup                interface{} `json:"DepreciationGroup"`
	AssetSerialNumber                string      `json:"AssetSerialNumber"`
	InventoryWeight                  float64     `json:"InventoryWeight"`
	InventoryWeightUnit              interface{} `json:"InventoryWeightUnit"`
	InventoryWeight1                 float64     `json:"InventoryWeight1"`
	InventoryWeightUnit1             interface{} `json:"InventoryWeightUnit1"`
	DefaultCountingUnit              interface{} `json:"DefaultCountingUnit"`
	CountingItemsPerUnit             float64     `json:"CountingItemsPerUnit"`
	DefaultCountingUoMEntry          interface{} `json:"DefaultCountingUoMEntry"`
	Excisable                        string      `json:"Excisable"`
	ChapterID                        int         `json:"ChapterID"`
	ScsCode                          interface{} `json:"ScsCode"`
	SpProdType                       interface{} `json:"SpProdType"`
	ProdStdCost                      float64     `json:"ProdStdCost"`
	InCostRollup                     string      `json:"InCostRollup"`
	VirtualAssetItem                 string      `json:"VirtualAssetItem"`
	EnforceAssetSerialNumbers        string      `json:"EnforceAssetSerialNumbers"`
	AttachmentEntry                  interface{} `json:"AttachmentEntry"`
	LinkedResource                   interface{} `json:"LinkedResource"`
	UpdateDate                       string      `json:"UpdateDate"`
	UpdateTime                       string      `json:"UpdateTime"`
	GSTRelevnt                       string      `json:"GSTRelevnt"`
	SACEntry                         int         `json:"SACEntry"`
	GSTTaxCategory                   string      `json:"GSTTaxCategory"`
	ServiceCategoryEntry             int         `json:"ServiceCategoryEntry"`
	CapitalGoodsOnHoldPercent        interface{} `json:"CapitalGoodsOnHoldPercent"`
	CapitalGoodsOnHoldLimit          interface{} `json:"CapitalGoodsOnHoldLimit"`
	AssessableValue                  float64     `json:"AssessableValue"`
	AssVal4WTR                       float64     `json:"AssVal4WTR"`
	SOIExcisable                     string      `json:"SOIExcisable"`
	Tnved                            interface{} `json:"TNVED"`
	ImportedItem                     string      `json:"ImportedItem"`
	PricingUnit                      int         `json:"PricingUnit"`
	CreateDate                       string      `json:"CreateDate"`
	CreateTime                       string      `json:"CreateTime"`
	NVECode                          interface{} `json:"NVECode"`
	CtrSealQty                       float64     `json:"CtrSealQty"`
	CESTCode                         int         `json:"CESTCode"`
	LegalText                        interface{} `json:"LegalText"`
	ItemPrices                       []struct {
		PriceList           int           `json:"PriceList"`
		Price               float64       `json:"Price"`
		Currency            interface{}   `json:"Currency"`
		AdditionalPrice1    float64       `json:"AdditionalPrice1"`
		AdditionalCurrency1 interface{}   `json:"AdditionalCurrency1"`
		AdditionalPrice2    float64       `json:"AdditionalPrice2"`
		AdditionalCurrency2 interface{}   `json:"AdditionalCurrency2"`
		BasePriceList       int           `json:"BasePriceList"`
		Factor              float64       `json:"Factor"`
		UoMPrices           []interface{} `json:"UoMPrices"`
	} `json:"ItemPrices"`
	ItemWarehouseInfoCollection []struct {
		MinimalStock                        float64       `json:"MinimalStock"`
		MaximalStock                        float64       `json:"MaximalStock"`
		MinimalOrder                        float64       `json:"MinimalOrder"`
		StandardAveragePrice                float64       `json:"StandardAveragePrice"`
		Locked                              string        `json:"Locked"`
		InventoryAccount                    interface{}   `json:"InventoryAccount"`
		CostAccount                         interface{}   `json:"CostAccount"`
		TransferAccount                     interface{}   `json:"TransferAccount"`
		RevenuesAccount                     interface{}   `json:"RevenuesAccount"`
		VarienceAccount                     interface{}   `json:"VarienceAccount"`
		DecreasingAccount                   interface{}   `json:"DecreasingAccount"`
		IncreasingAccount                   interface{}   `json:"IncreasingAccount"`
		ReturningAccount                    interface{}   `json:"ReturningAccount"`
		ExpensesAccount                     interface{}   `json:"ExpensesAccount"`
		EURevenuesAccount                   interface{}   `json:"EURevenuesAccount"`
		EUExpensesAccount                   interface{}   `json:"EUExpensesAccount"`
		ForeignRevenueAcc                   interface{}   `json:"ForeignRevenueAcc"`
		ForeignExpensAcc                    interface{}   `json:"ForeignExpensAcc"`
		ExemptIncomeAcc                     interface{}   `json:"ExemptIncomeAcc"`
		PriceDifferenceAcc                  interface{}   `json:"PriceDifferenceAcc"`
		WarehouseCode                       string        `json:"WarehouseCode"`
		InStock                             float64       `json:"InStock"`
		Committed                           float64       `json:"Committed"`
		Ordered                             float64       `json:"Ordered"`
		CountedQuantity                     float64       `json:"CountedQuantity"`
		WasCounted                          string        `json:"WasCounted"`
		UserSignature                       int           `json:"UserSignature"`
		Counted                             float64       `json:"Counted"`
		ExpenseClearingAct                  interface{}   `json:"ExpenseClearingAct"`
		PurchaseCreditAcc                   interface{}   `json:"PurchaseCreditAcc"`
		EUPurchaseCreditAcc                 interface{}   `json:"EUPurchaseCreditAcc"`
		ForeignPurchaseCreditAcc            interface{}   `json:"ForeignPurchaseCreditAcc"`
		SalesCreditAcc                      interface{}   `json:"SalesCreditAcc"`
		SalesCreditEUAcc                    interface{}   `json:"SalesCreditEUAcc"`
		ExemptedCredits                     interface{}   `json:"ExemptedCredits"`
		SalesCreditForeignAcc               interface{}   `json:"SalesCreditForeignAcc"`
		ExpenseOffsettingAccount            interface{}   `json:"ExpenseOffsettingAccount"`
		WipAccount                          interface{}   `json:"WipAccount"`
		ExchangeRateDifferencesAcct         interface{}   `json:"ExchangeRateDifferencesAcct"`
		GoodsClearingAcct                   interface{}   `json:"GoodsClearingAcct"`
		NegativeInventoryAdjustmentAccount  interface{}   `json:"NegativeInventoryAdjustmentAccount"`
		CostInflationOffsetAccount          interface{}   `json:"CostInflationOffsetAccount"`
		GLDecreaseAcct                      interface{}   `json:"GLDecreaseAcct"`
		GLIncreaseAcct                      interface{}   `json:"GLIncreaseAcct"`
		PAReturnAcct                        interface{}   `json:"PAReturnAcct"`
		PurchaseAcct                        interface{}   `json:"PurchaseAcct"`
		PurchaseOffsetAcct                  interface{}   `json:"PurchaseOffsetAcct"`
		ShippedGoodsAccount                 interface{}   `json:"ShippedGoodsAccount"`
		StockInflationOffsetAccount         interface{}   `json:"StockInflationOffsetAccount"`
		StockInflationAdjustAccount         interface{}   `json:"StockInflationAdjustAccount"`
		VATInRevenueAccount                 interface{}   `json:"VATInRevenueAccount"`
		WipVarianceAccount                  interface{}   `json:"WipVarianceAccount"`
		CostInflationAccount                interface{}   `json:"CostInflationAccount"`
		WHIncomingCenvatAccount             interface{}   `json:"WHIncomingCenvatAccount"`
		WHOutgoingCenvatAccount             interface{}   `json:"WHOutgoingCenvatAccount"`
		StockInTransitAccount               interface{}   `json:"StockInTransitAccount"`
		WipOffsetProfitAndLossAccount       interface{}   `json:"WipOffsetProfitAndLossAccount"`
		InventoryOffsetProfitAndLossAccount interface{}   `json:"InventoryOffsetProfitAndLossAccount"`
		DefaultBin                          interface{}   `json:"DefaultBin"`
		DefaultBinEnforced                  string        `json:"DefaultBinEnforced"`
		PurchaseBalanceAccount              interface{}   `json:"PurchaseBalanceAccount"`
		ItemCode                            string        `json:"ItemCode"`
		IndEscala                           string        `json:"IndEscala"`
		CNJPMan                             interface{}   `json:"CNJPMan"`
		ItemCycleCounts                     []interface{} `json:"ItemCycleCounts"`
	} `json:"ItemWarehouseInfoCollection"`
	ItemPreferredVendors            []interface{} `json:"ItemPreferredVendors"`
	ItemLocalizationInfos           []interface{} `json:"ItemLocalizationInfos"`
	ItemProjects                    []interface{} `json:"ItemProjects"`
	ItemDistributionRules           []interface{} `json:"ItemDistributionRules"`
	ItemAttributeGroups             []interface{} `json:"ItemAttributeGroups"`
	ItemDepreciationParameters      []interface{} `json:"ItemDepreciationParameters"`
	ItemPeriodControls              []interface{} `json:"ItemPeriodControls"`
	ItemUnitOfMeasurementCollection []interface{} `json:"ItemUnitOfMeasurementCollection"`
	ItemBarCodeCollection           []interface{} `json:"ItemBarCodeCollection"`
	ItemIntrastatExtension          struct {
		ItemCode                   string      `json:"ItemCode"`
		CommodityCode              interface{} `json:"CommodityCode"`
		SupplementaryUnit          interface{} `json:"SupplementaryUnit"`
		FactorOfSupplementaryUnit  float64     `json:"FactorOfSupplementaryUnit"`
		ImportRegionState          interface{} `json:"ImportRegionState"`
		ExportRegionState          interface{} `json:"ExportRegionState"`
		ImportNatureOfTransaction  interface{} `json:"ImportNatureOfTransaction"`
		ExportNatureOfTransaction  interface{} `json:"ExportNatureOfTransaction"`
		ImportStatisticalProcedure interface{} `json:"ImportStatisticalProcedure"`
		ExportStatisticalProcedure interface{} `json:"ExportStatisticalProcedure"`
		CountryOfOrigin            interface{} `json:"CountryOfOrigin"`
		ServiceCode                interface{} `json:"ServiceCode"`
		Type                       string      `json:"Type"`
		ServiceSupplyMethod        string      `json:"ServiceSupplyMethod"`
		ServicePaymentMethod       string      `json:"ServicePaymentMethod"`
		ImportRegionCountry        string      `json:"ImportRegionCountry"`
		ExportRegionCountry        string      `json:"ExportRegionCountry"`
		UseWeightInCalculation     string      `json:"UseWeightInCalculation"`
		IntrastatRelevant          string      `json:"IntrastatRelevant"`
		StatisticalCode            interface{} `json:"StatisticalCode"`
	} `json:"ItemIntrastatExtension"`
}
